repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: check-case-conflict
      - id: trailing-whitespace
      - id: check-toml
      - id: check-merge-conflict
      - id: check-added-large-files
        args: [--maxkb=3000]
      - id: check-merge-conflict
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        args: [--skip-string-normalization]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.291
    hooks:
      - id: ruff
        args: [--fix]
  - repo: https://github.com/crate-ci/typos
    rev: v1.16.14
    hooks:
      - id: typos
