name: llm_ui_env

dependencies:
  - langchain
  - streamlit
  - chromadb
  - pytorch
  - openai
  - tiktoken
  - python-dotenv
  - lorem
  - PyPDF2
  - huggingface_hub
  - pip
  - pip:
      - faiss-cpu
      - sentence_transformers
      - InstructorEmbedding
  - pytest
  - pre-commit
  - python=3.11
  - ruff
  - black
  - mypy
